version: '3.9'
services:
  tranning_db:
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=db_training
  tranning_mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  postgres:
